repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-print]
        args: ["--ignore=E501,W503,E203"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.0
    hooks:
      - id: poetry-sort

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
      - id: eslint
        files: \.(ts|vue)$
        types: [file]
        args: [--fix, --quiet]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@6.2.1"
          - "@typescript-eslint/eslint-plugin@6.2.1"
          - "@typescript-eslint/parser@6.2.1"
          - "@vue/eslint-config-typescript@11.0.3"
          - eslint-config-prettier@9.0.0
          - eslint-plugin-prettier@5.0.0
          - eslint-plugin-simple-import-sort@10.0.0
          - eslint-plugin-vue@9.16.1
          - eslint@8.46.0
