repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.0
    hooks:
      - id: poetry-sort

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
      - id: eslint
        files: \.(ts|vue)$
        types: [file]
        args: [--fix, --quiet]
        additional_dependencies:
          - "@rushstack/eslint-patch@1.5.1"
          - "@typescript-eslint/eslint-plugin@6.9.0"
          - "@typescript-eslint/parser@6.9.0"
          - "@vue/eslint-config-prettier@8.0.0"
          - "@vue/eslint-config-typescript@12.0.0"
          - eslint-config-prettier@9.0.0
          - eslint-plugin-prettier@5.0.1
          - eslint-plugin-simple-import-sort@10.0.0
          - eslint-plugin-vue@9.18.1
          - eslint@8.52.0
